# Generated by Django 4.0 on 2024-04-30 21:49

from django.db import migrations
from django.contrib.auth.hashers import make_password


def create_users(apps, schema_editor):
    """
    Create users.

    :param apps:
    :param schema_editor:
    """
    _User = apps.get_model('users', 'User')

    users = [
        _User(
            first_name='Admin', last_name='User', email='admin@example.com', password=make_password('Admin1234'),
            is_staff=True,
        ),
        _User(
            first_name='Tax', last_name='User', email='tax.user@example.com', password=make_password('Admin1234'),
            is_staff=True,
        ),
        _User(
            first_name='Kashif', last_name='Ali', email='kashif.ali@example.com', password=make_password('Admin1234'),
            is_staff=True,
        ),
        _User(
            first_name='Asif', last_name='Ali', email='asif.ali@example.com', password=make_password('Admin1234'),
            is_staff=True,
        ),
        _User(
            first_name='Nawaz', last_name='Shah', email='nawaz.shah@example.com', password=make_password('Admin1234'),
            is_staff=True,
        ),
    ]

    _User.objects.bulk_create(users)


def remove_users(apps, schema_editor):
    """
    Remove users.

    :param apps:
    :param schema_editor:
    """
    _User = apps.get_model('users', 'User')
    emails = [
        'admin@example.com', 'tax.user@example.com', 'kashif.ali@example.com', 'asif.ali@example.com',
        'nawaz.shah@example.com'
    ]
    _User.objects.filter(email__in=emails).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_users, remove_users),
    ]
