# Generated by Django 4.0 on 2024-04-29 20:12

import chats.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageattachment',
            name='attachment',
            field=models.FileField(upload_to=chats.utils.attachment_uploading_path),
        ),
        migrations.AlterField(
            model_name='messageattachment',
            name='message',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chats.messageprompt'),
        ),
    ]
