# Generated by Django 4.0 on 2024-04-29 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('chats', '0002_alter_messageattachment_attachment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageattachment',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
    ]
