# Generated by Django 4.0 on 2024-04-30 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_messageattachment_uploaded_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageattachment',
            name='message',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_attachment', to='chats.messageprompt'),
        ),
    ]
