# Generated by Django 4.0 on 2024-04-30 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_alter_messageattachment_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageprompt',
            name='role',
            field=models.IntegerField(choices=[(1, 'user'), (2, 'system')], default=1),
            preserve_default=False,
        ),
    ]
