# Generated by Django 4.0 on 2024-05-01 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20240430_2149'),
        ('chats', '0006_auto_20240430_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageprompt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_prompts', to='users.user'),
        ),
    ]
